# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('kategory_name', models.CharField(max_length=250, verbose_name='Kateqoriya adı')),
                ('kat_url', models.CharField(max_length=250, verbose_name='Kateqoriya yolu (url)')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, verbose_name='Başlıq')),
                ('body', models.TextField(verbose_name='Mətin qismi')),
                ('picture', models.ImageField(upload_to='', verbose_name='Şəkil')),
                ('created_at', models.DateTimeField(verbose_name='İndiki vaxt')),
                ('kat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Kategory')),
            ],
        ),
    ]
